# Generated by Django 4.2.3 on 2023-07-11 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kitap",
            options={
                "ordering": ["-created"],
                "verbose_name": "Kitap",
                "verbose_name_plural": "Kitaplar",
            },
        ),
        migrations.RemoveField(
            model_name="yazar",
            name="kitaplar",
        ),
        migrations.AddField(
            model_name="kitap",
            name="book_detail",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="kitap",
            name="book_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="kitap",
            name="created",
            field=models.DateTimeField(null=True, verbose_name="date created"),
        ),
        migrations.AddField(
            model_name="kitap",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="kitap",
            name="yazar",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app1.yazar"
            ),
        ),
        migrations.AddField(
            model_name="yazar",
            name="created",
            field=models.DateTimeField(null=True, verbose_name="date created"),
        ),
    ]
